---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "redis"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "redis"

- name: Copying over redis.conf
  template:
    src: "{{ item }}.j2"
    dest: "{{ node_config_directory }}/redis/{{ item }}"
  with_items:
    - "redis.conf"
