########
# Docker
########
kafka_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-kafka"
kafka_tag: "{{ openstack_release }}"
kafka_image_full: "{{ kafka_image }}:{{ kafka_tag }}"
