---
####################
# Docker
####################
redis_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-redis"
redis_tag: "{{ openstack_release }}"
redis_image_full: "{{ redis_image }}:{{ redis_tag }}"

####################
# Mongodb
####################

