---
project_name: "cassandra"

########
# Docker
########
cassandra_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-cassandra"
cassandra_tag: "{{ openstack_release }}"
cassandra_image_full: "{{ cassandra_image }}:{{ cassandra_tag }}"

############
# Cassandra
############
cassandra_native_port: 9042
